#consul 服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-pament
######consul 注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.
        service-name: ${spring.application.name}
